const CART_ACTION_TYPES = {
  SET_IS_CART_OPEN: "cart/SET_IS_CART_OPEN",
  SET_CART_ITEMS: "cart/SET_CART_ITEMS",
  SET_CART_TOTAL_ITEM: "cart/SET_CART_TOTAL_ITEM",
  SET_CART_TOTAL_PRICE: "cart/SET_CART_TOTAL_PRICE",
};

export default CART_ACTION_TYPES;
